// Access Contol List
// UPLOADS ???


// allow - полный доступ 
// self - только для владельца или РОПа 
// forbid - запрещено
const rights = {
  1: {
    'GET': {
      '/teachers': 'allow', 
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow',
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'POST': {
      '/teachers': 'forbid',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'forbid', 
      '/uploads/ind_plan': 'forbid',
      '/uploads/projects': 'forbid',
      '/uploads/rpd': 'forbid',
      '/uploads/acad_plan': 'forbid',
      '/uploads/dep_load': 'forbid', 
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'PUT': {
      '/teachers': 'self',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'forbid', 
      '/uploads/ind_plan': 'forbid',
      '/uploads/projects': 'forbid',
      '/uploads/rpd': 'forbid',
      '/uploads/acad_plan': 'forbid',
      '/uploads/dep_load': 'forbid', 
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'DELETE': {
      '/teachers': 'forbid',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'forbid', 
      '/uploads/ind_plan': 'forbid',
      '/uploads/projects': 'forbid',
      '/uploads/rpd': 'forbid',
      '/uploads/acad_plan': 'forbid',
      '/uploads/dep_load': 'forbid', 
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    }
  },
  2: {
    'GET': {
      '/teachers': 'allow', 
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow',
      '/uploads/dep_load': 'allow', 
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'POST': {
      '/teachers': 'forbid',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'forbid', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'PUT': {
      '/teachers': 'self',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'self', 
      '/uploads/ind_plan': 'self',
      '/uploads/projects': 'self',
      '/uploads/rpd': 'self',
      '/uploads/acad_plan': 'self',
      '/uploads/dep_load': 'self', 
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'DELETE': {
      '/teachers': 'forbid',
      '/students': 'forbid', 
      '/groups': 'forbid', 
      '/specialties': 'forbid', 
      '/acad_plan': 'forbid', 
      '/dep_load': 'forbid', 
      '/projects': 'forbid', 
      '/uploads/ind_plan': 'self',
      '/uploads/projects': 'self',
      '/uploads/rpd': 'self',
      '/uploads/acad_plan': 'self', 
      '/uploads/dep_load': 'self', 
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    }
  },
  3: {
    'GET': {
      '/teachers': 'allow', 
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'POST': {
      '/teachers': 'forbid',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'PUT': {
      '/teachers': 'self',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    },
    'DELETE': {
      '/teachers': 'forbid',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'forbid',
      '/ranks': 'forbid',
      '/degree': 'forbid',
      '/sub_unit': 'forbid'
    }
  },
  4: {
    'GET': {
      '/teachers': 'allow', 
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'POST': {
      '/teachers': 'allow',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'PUT': {
      '/teachers': 'allow',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    },
    'DELETE': {
      '/teachers': 'allow',
      '/students': 'allow', 
      '/groups': 'allow', 
      '/specialties': 'allow', 
      '/acad_plan': 'allow', 
      '/dep_load': 'allow', 
      '/projects': 'allow', 
      '/uploads/ind_plan': 'allow',
      '/uploads/projects': 'allow',
      '/uploads/rpd': 'allow',
      '/uploads/acad_plan': 'allow', 
      '/uploads/dep_load': 'allow',
      '/department': 'allow',
      '/ranks': 'allow',
      '/degree': 'allow',
      '/sub_unit': 'allow'
    }
  }
};

module.exports = rights;